app/models/entry.py
from app import db

class Entry(db.Model):
    id = db.Column(db.Integer, primary_key = True) # Entry ID.
    slug = db.Column(db.String(100), nullable = False, unique = True) # Entry Slug.
    title = db.Column(db.String(100), nullable = False) # Entry Title.
    content = db.Column(db.Text, nullable = False) # Entry Content.
    is_active = db.Column(db.Boolean, nullable = False, default = True) # Entry Activate.
    created_at = db.Column(
        db.DateTime, nullable = False, default = db.func.now(),
        server_default = db.func.now()
    ) # Entry Create Date.
    updated_at = db.Column(
        db.DateTime, nullable = False, default = db.func.now(),
        server_default = db.func.now(), server_onupdate = db.func.now()
    ) # Entry Modify Date.

app/models/page.py
from app import db

class Page(db.Model):
    id = db.Column(db.Integer, primary_key = True) # Page ID.
    slug = db.Column(db.String(100), nullable = False, unique = True) # Page Slug.
    title = db.Column(db.String(100), nullable = False) # Page Title.
    content = db.Column(db.Text, nullable = False) # Page Content.
    is_active = db.Column(db.Boolean, nullable = False, default = True) # Page Activate.
    created_at = db.Column(
        db.DateTime, nullable = False, default = db.func.now(),
        server_default = db.func.now()
    ) # Psge Create Date.
    updated_at = db.Column(
        db.DateTime, nullable = False, default = db.func.now(),
        server_default = db.func.now(), server_onupdate = db.func.now()
    ) # Page Modify Date.

app/models/user.py
from app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key = True) # User ID.
    email = db.Column(db.String(70), nullable = False, unique = True) # User E-Mail.
    password = db.Column(db.String(32), nullable = False) # User Password.
    name = db.Column(db.String(30), nullable = False) # User Name.
    note = db.Column(db.Text, nullable = True) # User Note.
    created_at = db.Column(db.DateTime, default = db.func.now(), nullable = False) # User Create Date.

    def generate_password_hash(self, password):
        """
            This function is for securely generating password digits.
        """
        self.password = generate_password_hash(password)

    def check_password(self, password):
        """
            This function has been added for login verification.
        """
        return check_password_hash(self.password, password)

app/forms/auth.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Email

class LoginForm(FlaskForm):
    email = StringField('E-Mail', validators = [DataRequired(), Email()], render_kw = {'placeholder': 'email:', 'autocomplete': 'off', 'value': 'email:'})
    password = PasswordField('Password', validators = [DataRequired()], render_kw = {'placeholder': 'password:', 'autocomplete': 'off', 'value': 'password:'})
    submit = SubmitField('[ submit ]')

app/__init__.py
from os import getenv

from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate

from config import Config

db = SQLAlchemy()
login_manager = LoginManager()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    @app.context_processor
    def context_processor():
        from app.models.page import Page
        header_pages = Page.query.filter_by(is_active = True).all()

        return dict(
            site_url = getenv('SITE_URL'),
            site_name = getenv('SITE_NAME'),
            site_title = getenv('SITE_TITLE'),
            site_desc = getenv('SITE_DESC'),
            site_signature = getenv('SITE_SIGNATURE'),
            site_twitter = getenv('SITE_TWITTER'),
            site_github = getenv('SITE_GITHUB'),
            header_pages = header_pages
        )

    db.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app, db)

    # Auth Routes
    from app.routes.auth import auth
    app.register_blueprint(auth)

    # Home Route
    from app.routes.home.main import h_main
    app.register_blueprint(h_main)

    from app.routes.home.entry import h_entry
    app.register_blueprint(h_entry)

    from app.routes.home.page import h_page
    app.register_blueprint(h_page)

    # Dashboard Routes
    from app.routes.dashboard.main import d_main
    app.register_blueprint(d_main)

    from app.routes.dashboard.entry import d_entry
    app.register_blueprint(d_entry)

    from app.routes.dashboard.page import d_page
    app.register_blueprint(d_page)

    return app

app/forms/dashboard/main.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class SettingsForm(FlaskForm):
    url = StringField('Sıte URL', validators = [DataRequired()], render_kw = {'placeholder': 'URL:', 'autocomplete': 'off'})
    name = StringField('Sıte Name', validators = [DataRequired()], render_kw = {'placeholder': 'Name:', 'autocomplete': 'off'})
    title = StringField('Sıte Title', validators = [DataRequired()], render_kw = {'placeholder': 'Title:', 'autocomplete': 'off'})
    desc = StringField('Sıte DESC', validators = [DataRequired()], render_kw = {'placeholder': 'Desc:', 'autocomplete': 'off'})
    signature = StringField('Sıte Signature', validators = [DataRequired()], render_kw = {'placeholder': 'Signature:', 'autocomplete': 'off'})
    twitter = StringField('Sıte Twitter', validators = [DataRequired()], render_kw = {'placeholder': 'Twitter:', 'autocomplete': 'off'})
    github = StringField('Sıte GitHub', validators = [DataRequired()], render_kw = {'placeholder': 'GitHub:', 'autocomplete': 'off'})
    submit = SubmitField('[ submit ]')

app/routes/auth.py
from flask import Blueprint, redirect, url_for, render_template, flash
from flask_login import logout_user, current_user, login_user

from app.models.user import User
from app.forms.auth import LoginForm

auth = Blueprint('auth', __name__, url_prefix='/auth')

@auth.route('/')
@auth.route('/index')
def index():
    return redirect(url_for('auth.login'))

@auth.route('/register')
def register():
    return 'ok'

@auth.route('/login', methods = ['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('d_main.index'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()

        if user is None or not user.check_password(form.password.data):
            flash('Login Failed')
        else:
            login_user(user)
            redirect(url_for('d_main.index'))

    return render_template('auth/login.html', title = 'Login', form = form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

app/routes/dashboard/main.py
from os import environ

from flask import Blueprint, render_template
from app.forms.dashboard.main import SettingsForm

d_main = Blueprint('d_main', __name__, url_prefix='/dashboard')

@d_main.route('/')
@d_main.route('/index', methods = ['GET', 'POST'])
def index():
    form = SettingsForm()

    if form.validate_on_submit():
        environ['SITE_URL'] = form.url.data
        environ['SITE_NAME'] = form.name.data
        environ['SITE_TITLE'] = form.title.data
        environ['SITE_DESC'] = form.desc.data
        environ['SITE_SIGNATURE'] = form.signature.data
        environ['SITE_TWITTER'] = form.twitter.data
        environ['SITE_GITHUB'] = form.github.data

    form.url.data = environ['SITE_URL']
    form.name.data = environ['SITE_NAME']
    form.title.data = environ['SITE_TITLE']
    form.desc.data = environ['SITE_DESC']
    form.signature.data = environ['SITE_SIGNATURE']
    form.twitter.data = environ['SITE_TWITTER']
    form.github.data = environ['SITE_GITHUB']

    return render_template('dashboard/main/index.html', title = 'Dashboard', form = form)

app/routes/home/main.py
from flask import Blueprint, render_template

from app.models.entry import Entry

h_main = Blueprint('h_main', __name__, url_prefix='/')

@h_main.route('/')
@h_main.route('/index')
def index():
    entries = Entry.query.order_by(Entry.created_at.desc()).all()
    return render_template('home/main/index.html', title = '/', entries = entries)

@h_main.route('/contact', methods = ['GET', 'POST'])
def contact():
    return render_template('home/main/contact.html', title = 'Contact')

app/templates/assets/dashboard_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>
        {% if title %}
            {{ title }}
        {% else %}
            /
        {% endif %}
    </title>
    <meta name="generator" content="Flask" />
    <meta property="og:title" content="/" />
    <meta property="og:locale" content="tr_TR" />
    <meta name="description" content="" />
    <meta property="og:description" content="" />
    <meta property="og:site_name" content="" />
    <link rel="stylesheet" type="text/css" href="/static/assets/css/dark.css">
</head>

<body>
    <div class="container">
        <header>

            {% include 'assets/dashboard_menu.html' %}
        </header>
        <main>
            {% block content %}

            {% endblock %}
        </main>
        <footer>
            follow us on <a href="https://twitter.com/{{ site_twitter }}">Twitter</a> and <a href="https://github.com/{{ site_github }}">GitHub</a>. Mode: <a href="">Dark</a>, <a href="">Light</a> or <a href="">Hacker</a>
        </footer>
    </div>
</body>

</html>

app/templates/assets/dashboard_menu.html
<div class="menu">
    <ul>
        <li>
            <a href="{{ url_for('d_main.index') }}">/dashboard</a>
        </li>
        <li>
            <a href="{{ url_for('d_entry.index') }}">/entry/index</a>
        </li>
        <li>
            <a href="{{ url_for('d_entry.create') }}">/entry/create</a>
        </li>
        <li>
            <a href="{{ url_for('d_page.index') }}">/page/index</a>
        </li>
        <li>
            <a href="{{ url_for('d_page.create') }}">/page/create</a>
        </li>
        <li>
            <a href="{{ url_for('auth.logout') }}">/logout</a>
        </li>
    </ul>
</div>

app/templates/assets/home_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>
        {% if title %}
            {{ title }}
        {% else %}
            /
        {% endif %}
    </title>
    <meta name="generator" content="Flask" />
    <meta property="og:title" content="/" />
    <meta property="og:locale" content="tr_TR" />
    <meta name="description" content="" />
    <meta property="og:description" content="" />
    <meta property="og:site_name" content="" />
    <link rel="stylesheet" type="text/css" href="/static/assets/css/dark.css">
</head>

<body>
    <div class="container">
        <header>

            {% include 'assets/home_menu.html' %}
        </header>
        <main>
            {% block content %}

            {% endblock %}
        </main>
        <footer>
            follow us on <a href="https://twitter.com/{{ site_twitter }}">Twitter</a> and <a href="https://github.com/{{ site_github }}">GitHub</a>. Mode: <a href="">Dark</a>, <a href="">Light</a> or <a href="">Hacker</a>
        </footer>
    </div>
</body>

</html>

app/templates/assets/home_menu.html
<div class="menu">
    <ul>
        <li>
            <a href="{{ url_for('h_main.index') }}">/</a>
        </li>
        {% if current_user.is_authenticated %}
            <li>
                <a href="{{ url_for('d_main.index') }}">/dashboard</a>
            </li>
        {% endif %}
        <li>
            <a href="{{ url_for('h_main.contact') }}">/contact</a>
        </li>
        {% for header_page in header_pages %}
            <li>
                <a href="{{ url_for('h_page.show', slug = header_page.slug) }}">/{{ header_page.slug }}</a>
            </li>
        {% endfor %}
    </ul>
</div>

app/templates/dashboard/entry/create.html
{% extends 'assets/dashboard_base.html' %}

{% block content %}
<h1 id="welcome">{{ title }}</h1>

<br />
<form action="" method="POST">
    {% with messages = get_flashed_messages(with_categories = True) %}
        {% if messages %}
            {% for category, message in messages %}
                {{ message }}
                <br>
            {% endfor %}
        {% endif %}
    {% endwith %}

    {{ form.hidden_tag() }}
    --> {{ form.title.label() }}
    {{ form.title() }}
    --> {{ form.slug.label() }}
    {{ form.slug() }}
    --> {{ form.content.label() }}
    {{ form.content() }}
    {{ form.submit() }}
</form>
{% endblock %}

app/templates/dashboard/entry/edit.html
{% extends 'assets/dashboard_base.html' %}

{% block content %}
<h1 id="welcome">{{ title }}</h1>

<br />
<form action="" method="POST">
    {% with messages = get_flashed_messages(with_categories = True) %}
        {% if messages %}
            {% for category, message in messages %}
                {{ message }}
                <br>
            {% endfor %}
        {% endif %}
    {% endwith %}

    {{ form.hidden_tag() }}
    --> {{ form.title.label() }}
    {{ form.title() }}
    --> {{ form.slug.label() }}
    {{ form.slug() }}
    --> {{ form.content.label() }}
    {{ form.content() }}
    {{ form.submit() }}
</form>
{% endblock %}

app/templates/dashboard/entry/index.html
{% extends 'assets/dashboard_base.html' %}

{% block content %}
<h1 id="welcome">{{ title }}</h1>

<br />
<ul>
    {% for entry in entries %}
        <li>[ {{ entry.created_at }} ] <a href="{{ url_for('d_entry.edit', slug = entry.slug) }}">{{ entry.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/dashboard/main/index.html
{% extends 'assets/dashboard_base.html' %}

{% block content %}
<h1 id="welcome">{{ title }}</h1>

<br />
<form action="" method="POST">
    {% with messages = get_flashed_messages(with_categories = True) %}
        {% if messages %}
            {% for category, message in messages %}
                {{ message }}
            {% endfor %}
        {% endif %}
    {% endwith %}

    {{ form.hidden_tag() }}
    --> {{ form.url.label() }}
    {{ form.url() }}
    --> {{ form.name.label() }}
    {{ form.name() }}
    --> {{ form.title.label() }}
    {{ form.title() }}
    --> {{ form.desc.label() }}
    {{ form.desc() }}
    --> {{ form.signature.label() }}
    {{ form.signature() }}
    --> {{ form.twitter.label() }}
    {{ form.twitter() }}
    --> {{ form.github.label() }}
    {{ form.github() }}
    {{ form.submit() }}
</form>
{% endblock %}

app/templates/home/entry/index.html
{% extends 'assets/home_base.html' %}

{% block content %}
<h1 id="welcome">Yunus Emre Geldegül, (I think) Backend Developer.</h1>
<p>Respect For The Suffering One.</p>

<br />
<ul>
    {% for entry in entries %}
        <li>[ {{ entry.created_at }} ] <a href="{{ url_for('h_entry.show', slug = entry.slug) }}">{{ entry.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/home/entry/show.html
{% extends 'assets/home_base.html' %}

{% block content %}
<h1 id="welcome">{{ title }}</h1>

<br />
{{ entry.content | safe }}
{% endblock %}

app/templates/home/main/contact.html
{% extends 'assets/home_base.html' %}

{% block content %}
<h1 id="get-in-touch">Contact</h1>

<form action="" method="POST">
    <input type="text" id="name" name="name" placeholder="name:" autocomplete="off" />
    <input type="text" id="email" name="email" placeholder="email:" autocomplete="off" />
    <textarea rows="5" id="message" name="message" placeholder="message:" autocomplete="off"></textarea>
    <input type="submit" value="[ submit ]" onclick="()"/>
</form>
<br>
<br>
<p>Reminder: This form does not work ;)</p>
{% endblock %}

app/templates/home/main/index.html
{% extends 'assets/home_base.html' %}

{% block content %}
<h1 id="welcome">{{ site_name }}</h1>
<p>{{ site_signature }}</p>

<br />
<ul>
    {% for entry in entries %}
        <li>[ {{ entry.created_at }} ] <a href="{{ url_for('h_entry.show', slug = entry.slug) }}">{{ entry.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/home/page/index.html
{% extends 'assets/home_base.html' %}

{% block content %}
<ul>
    {% for entry in entries %}
        <li>[ {{ entry.created_at }} ] <a href="{{ url_for('h_entry.show', slug = entry.slug) }}">{{ entry.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/home/page/show.html
{% extends 'assets/home_base.html' %}

{% block content %}
<h1 id="welcome">{{ title }}</h1>

<br />
{{ page.content }}
{% endblock %}